'use client'

import { Image as ImageIcon, Sparkles, Boxes, SlidersHorizontal, Check } from 'lucide-react'
import { Reveal } from '@/components/motion'
import { SectionTag } from '@/components/ui'
import { useT, type Dict } from '@/lib/i18n'
import { cn } from '@/lib/utils'

const M: Dict = {
  '지금 제작되는 AI 사진': { en: 'AI photos in production now', ja: '今つくられているAI写真', zh: '此刻正在生成的 AI 图片' },
  '모든 최상위 이미지 모델로,': { en: 'With every top-tier image model,', ja: 'すべての最上位画像モデルで、', zh: '用所有顶级图像模型，' },
  '노드형 파이프라인에서': { en: 'in a node-based pipeline', ja: 'ノード型パイプラインで', zh: '在节点式流水线中' },
  '프롬프트 한 줄이 레퍼런스 이미지 → 정밀 편집 → 최상위 이미지 모델을 거쳐 완성됩니다. 각 모델로 실제 생성되는 사진들입니다.': {
    en: 'A single prompt flows through a reference image → precise editing → top-tier image models. These are photos actually generated by each model.',
    ja: '一行のプロンプトがレファレンス画像→精密編集→最上位の画像モデルを経て完成します。各モデルで実際に生成される写真です。',
    zh: '一句提示词经过参考图 → 精准编辑 → 顶级图像模型完成。这些是各模型实际生成的图片。',
  },
  '노드형': { en: 'Node-based', ja: 'ノード型', zh: '节点式' },
  '레퍼런스 편집': { en: 'Reference edit', ja: 'レファレンス編集', zh: '参考编辑' },
  '4K 고해상도': { en: '4K high-res', ja: '4K高解像度', zh: '4K 高清' },
  '작동 중': { en: 'Live', ja: '稼働中', zh: '运行中' },
  // 씬 캡션
  '모터스포츠 광고컷': { en: 'Motorsport ad shot', ja: 'モータースポーツ広告', zh: '赛车运动广告' },
  '스타디움 현장 스케치': { en: 'Stadium scene', ja: 'スタジアム現場', zh: '球场现场' },
  '의료 상담 컷': { en: 'Medical consultation', ja: '医療相談カット', zh: '医疗咨询' },
  '관중 클로즈업': { en: 'Crowd close-up', ja: '観客クローズアップ', zh: '观众特写' },
  '스포츠 액션': { en: 'Sports action', ja: 'スポーツアクション', zh: '运动瞬间' },
  '제품 광고 클로즈업': { en: 'Product ad close-up', ja: '製品広告クローズアップ', zh: '产品广告特写' },
  '인물 시네마틱 포트레이트': { en: 'Cinematic portrait', ja: 'シネマティックポートレート', zh: '电影感人像' },
  '브랜드 필름 스틸': { en: 'Brand film still', ja: 'ブランドフィルムスチル', zh: '品牌影片剧照' },
  '패션 룩북': { en: 'Fashion lookbook', ja: 'ファッションルックブック', zh: '时尚 Lookbook' },
  '도시 야경 스틸': { en: 'City night still', ja: '都市夜景スチル', zh: '城市夜景' },
  '뷰티 제품 광고': { en: 'Beauty product ad', ja: 'ビューティー製品広告', zh: '美妆产品广告' },
  '사진 예시는 각 모델로 생성한 결과물이며, 실제 서비스에서는 여러분의 레퍼런스로 생성한 사진으로 대체됩니다.': {
    en: 'Sample photos are outputs of each model; in the product these are replaced by photos generated from your own references.',
    ja: '写真例は各モデルの生成結果で、実サービスでは皆さんのレファレンスで生成した写真に置き換わります。',
    zh: '示例图片为各模型的生成结果；正式服务中将替换为用您的参考生成的图片。',
  },
}

type Shot = {
  cap: string
  model: string
  ar: 'p' | 'l' | 's' // portrait 9:16, landscape 16:9, square
  grad: string
  glow: string
  tag?: 'node' | 'control'
  src: string
}

/** 홈 쇼케이스 사진 — public/images/showcase/ 에 파일을 넣으면 자동으로 표시되고,
 *  없으면 그라데이션 포스터가 폴백으로 유지됩니다. */
const SHOTS: Shot[] = [
  { cap: '모터스포츠 광고컷', model: 'Nano Banana', ar: 'l', src: '/images/showcase/1.png', grad: 'from-red-600 via-rose-600 to-slate-800', glow: 'radial-gradient(circle at 30% 30%, rgba(255,180,150,0.55), transparent 45%)', tag: 'node' },
  { cap: '스타디움 현장 스케치', model: 'GPT Image 2', ar: 'p', src: '/images/showcase/2.png', grad: 'from-slate-800 via-indigo-800 to-amber-500', glow: 'radial-gradient(circle at 50% 25%, rgba(255,230,170,0.5), transparent 42%)' },
  { cap: '의료 상담 컷', model: 'Flux 1.1 Pro', ar: 'l', src: '/images/showcase/3.png', grad: 'from-sky-700 via-slate-600 to-slate-200', glow: 'radial-gradient(circle at 65% 30%, rgba(210,230,255,0.5), transparent 45%)', tag: 'control' },
  { cap: '관중 클로즈업', model: 'Nano Banana', ar: 'l', src: '/images/showcase/4.png', grad: 'from-slate-900 via-blue-900 to-slate-700', glow: 'radial-gradient(circle at 45% 30%, rgba(150,180,255,0.5), transparent 45%)' },
  { cap: '스포츠 액션', model: 'GPT Image', ar: 'l', src: '/images/showcase/5.png', grad: 'from-zinc-900 via-neutral-800 to-orange-700', glow: 'radial-gradient(circle at 60% 35%, rgba(255,160,110,0.5), transparent 45%)', tag: 'node' },
  { cap: '브랜드 필름 스틸', model: 'Flux Kontext', ar: 'l', src: '/images/showcase/6.png', grad: 'from-slate-800 via-zinc-700 to-blue-800', glow: 'radial-gradient(circle at 40% 30%, rgba(160,190,255,0.5), transparent 45%)', tag: 'control' },
  { cap: '제품 광고 클로즈업', model: 'Runway Gen-4', ar: 'l', src: '/images/showcase/7.png', grad: 'from-slate-700 via-zinc-600 to-amber-500', glow: 'radial-gradient(circle at 60% 30%, rgba(255,255,255,0.5), transparent 40%)' },
  { cap: '도시 야경 스틸', model: 'Nano Banana', ar: 'l', src: '/images/showcase/8.png', grad: 'from-blue-800 via-indigo-800 to-purple-800', glow: 'radial-gradient(circle at 30% 70%, rgba(120,160,255,0.55), transparent 45%)', tag: 'node' },
  { cap: '인물 시네마틱 포트레이트', model: 'GPT Image 2', ar: 'l', src: '/images/showcase/9.png', grad: 'from-rose-500 via-purple-600 to-slate-900', glow: 'radial-gradient(circle at 50% 30%, rgba(255,200,230,0.5), transparent 42%)', tag: 'control' },
  { cap: '뷰티 제품 광고', model: 'Flux 1.1 Pro', ar: 'l', src: '/images/showcase/10.png', grad: 'from-rose-400 via-pink-500 to-purple-600', glow: 'radial-gradient(circle at 55% 28%, rgba(255,225,235,0.6), transparent 40%)' },
  { cap: '패션 룩북', model: 'GPT Image 2', ar: 'p', src: '/images/showcase/2.png', grad: 'from-pink-500 via-fuchsia-600 to-violet-700', glow: 'radial-gradient(circle at 50% 20%, rgba(255,210,240,0.5), transparent 42%)' },
  { cap: '모터스포츠 광고컷', model: 'Nano Banana', ar: 'l', src: '/images/showcase/1.png', grad: 'from-red-600 via-rose-600 to-slate-800', glow: 'radial-gradient(circle at 30% 30%, rgba(255,180,150,0.55), transparent 45%)', tag: 'node' },
  { cap: '스포츠 액션', model: 'GPT Image', ar: 'l', src: '/images/showcase/5.png', grad: 'from-zinc-900 via-neutral-800 to-orange-700', glow: 'radial-gradient(circle at 60% 35%, rgba(255,160,110,0.5), transparent 45%)' },
]

const ARW: Record<Shot['ar'], string> = { p: 'w-44', l: 'w-80', s: 'w-56' }

const LEGEND = ['Nano Banana', 'GPT Image 2', 'Flux 1.1 Pro Ultra', 'Flux Kontext Max', 'Grok Imagine', 'Runway Gen-4']

function ShotCard({ c, t }: { c: Shot; t: (s: string) => string }) {
  return (
    <div className={cn('group relative h-56 overflow-hidden rounded-xl border border-white/10 shadow-lg transition-transform duration-300 hover:scale-[1.03]', ARW[c.ar])}>
      {/* 그라데이션 포스터 (이미지 로딩 전 / 파일 없을 때 폴백) */}
      <div className={cn('absolute inset-0 bg-gradient-to-br', c.grad)} />
      <div className="absolute inset-0" style={{ backgroundImage: c.glow }} />

      {/* 실제 사진 (파일이 있으면 표시, 없으면 onError 로 숨겨져 포스터가 보임) */}
      <img
        src={c.src}
        alt={t(c.cap)}
        loading="lazy"
        className="absolute inset-0 h-full w-full object-cover"
        onError={(e) => { e.currentTarget.style.display = 'none' }}
      />

      <div className="absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-black/70 via-black/20 to-transparent" />

      {/* 모델 배지 */}
      <span className="absolute left-2 top-2 flex items-center gap-1 rounded-md bg-black/45 px-1.5 py-0.5 text-[10px] font-bold text-white backdrop-blur-sm">
        <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" /> {c.model}
      </span>
      {/* 태그 */}
      {c.tag && (
        <span className="absolute right-2 top-2 rounded-md bg-blue-500/85 px-1.5 py-0.5 text-[9px] font-bold text-white backdrop-blur-sm">
          {c.tag === 'node' ? t('노드형') : t('레퍼런스 편집')}
        </span>
      )}
      {/* 하단 캡션 */}
      <div className="absolute inset-x-0 bottom-0 flex items-end justify-between p-2.5">
        <span className="max-w-[75%] text-[11px] font-medium leading-tight text-white [text-shadow:0_1px_4px_rgba(0,0,0,0.6)]">{t(c.cap)}</span>
        <span className="rounded bg-white/20 px-1.5 py-0.5 text-[9px] font-bold text-white backdrop-blur-sm">AI</span>
      </div>
    </div>
  )
}

export function AIVideoGallery() {
  const t = useT(M)
  const row1 = SHOTS.slice(0, 6)
  const row2 = SHOTS.slice(6)
  return (
    <section className="relative overflow-hidden border-t border-white/10 py-24">
      <div className="relative mx-auto max-w-7xl px-5">
        <Reveal className="mx-auto max-w-2xl text-center">
          <SectionTag>
            <Sparkles size={13} /> {t('지금 제작되는 AI 사진')}
          </SectionTag>
          <h2 className="mt-5 break-keep text-balance text-4xl font-bold tracking-tight sm:text-5xl">
            {t('모든 최상위 이미지 모델로,')} <span className="brand-text">{t('노드형 파이프라인에서')}</span>
          </h2>
          <p className="mx-auto mt-5 max-w-xl break-keep text-balance text-lg leading-relaxed text-[var(--text-soft)]">
            {t('프롬프트 한 줄이 레퍼런스 이미지 → 정밀 편집 → 최상위 이미지 모델을 거쳐 완성됩니다. 각 모델로 실제 생성되는 사진들입니다.')}
          </p>

          {/* 특성 태그 */}
          <div className="mt-6 flex flex-wrap items-center justify-center gap-2">
            {[
              { icon: Boxes, label: t('노드형') },
              { icon: SlidersHorizontal, label: t('레퍼런스 편집') },
              { icon: ImageIcon, label: t('4K 고해상도') },
            ].map((x) => {
              const Icon = x.icon
              return (
                <span key={x.label} className="inline-flex flex-shrink-0 items-center gap-1.5 whitespace-nowrap rounded-full border border-white/12 bg-white/[0.05] px-3 py-1.5 text-xs font-semibold text-slate-200">
                  <Icon size={13} className="text-blue-300" /> {x.label}
                </span>
              )
            })}
          </div>
        </Reveal>
      </div>

      {/* 갤러리 (2행 마퀴, 좌우 반대 방향) */}
      <Reveal delay={100} className="mt-14 space-y-4">
        <div className="marquee-mask overflow-hidden">
          <div className="marquee-track gap-4">
            {[...row1, ...row1].map((c, i) => <div key={i} className="flex-shrink-0"><ShotCard c={c} t={t} /></div>)}
          </div>
        </div>
        <div className="marquee-mask overflow-hidden">
          <div className="marquee-track marquee-rev gap-4">
            {[...row2, ...row2].map((c, i) => <div key={i} className="flex-shrink-0"><ShotCard c={c} t={t} /></div>)}
          </div>
        </div>
      </Reveal>

      {/* 작동 중인 모델 레전드 */}
      <div className="relative mx-auto mt-12 max-w-4xl px-5">
        <p className="mb-3 flex items-center justify-center gap-2 text-xs font-semibold text-[var(--text-soft)]">
          <span className="relative flex h-2 w-2">
            <span className="animate-ping-ring absolute inline-flex h-full w-full rounded-full bg-emerald-400" />
            <span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-400" />
          </span>
          {t('작동 중')}
        </p>
        <div className="flex flex-wrap justify-center gap-2">
          {LEGEND.map((m) => (
            <span key={m} className="inline-flex items-center gap-1.5 rounded-full border border-white/12 bg-white/[0.05] px-3 py-1.5 text-xs font-medium text-slate-300">
              <Check size={12} className="text-emerald-400" /> {m}
            </span>
          ))}
        </div>
        <p className="mt-6 text-center text-[11px] leading-relaxed text-[var(--text-dim)]">
          {t('사진 예시는 각 모델로 생성한 결과물이며, 실제 서비스에서는 여러분의 레퍼런스로 생성한 사진으로 대체됩니다.')}
        </p>
      </div>
    </section>
  )
}
