'use client'

import { Play, Sparkles, Boxes, SlidersHorizontal, Check } from 'lucide-react'
import { Reveal } from '@/components/motion'
import { SectionTag } from '@/components/ui'
import { useT, type Dict } from '@/lib/i18n'
import { cn } from '@/lib/utils'

const M: Dict = {
  '지금 제작되는 AI 영상': { en: 'AI videos in production now', ja: '今つくられているAI動画', zh: '此刻正在生成的 AI 视频' },
  '모든 최상위 모델로,': { en: 'With every top-tier model,', ja: 'すべての最上位モデルで、', zh: '用所有顶级模型，' },
  '노드형 파이프라인에서': { en: 'in a node-based pipeline', ja: 'ノード型パイプラインで', zh: '在节点式流水线中' },
  '프롬프트 한 줄이 레퍼런스 이미지 → ControlNet 정밀 제어 → 최상위 영상 모델을 거쳐 완성됩니다. 각 모델로 실제 생성되는 영상들입니다.': {
    en: 'A single prompt flows through a reference image → precise ControlNet control → top-tier video models. These are videos actually generated by each model.',
    ja: '一行のプロンプトがレファレンス画像→ControlNet精密制御→最上位の動画モデルを経て完成します。各モデルで実際に生成される動画です。',
    zh: '一句提示词经过参考图 → ControlNet 精准控制 → 顶级视频模型完成。这些是各模型实际生成的视频。',
  },
  '노드형': { en: 'Node-based', ja: 'ノード型', zh: '节点式' },
  'ControlNet 제어': { en: 'ControlNet', ja: 'ControlNet制御', zh: 'ControlNet 控制' },
  '4K 렌더': { en: '4K render', ja: '4Kレンダー', zh: '4K 渲染' },
  '작동 중': { en: 'Live', ja: '稼働中', zh: '运行中' },
  // 씬 캡션
  '노을 해변, 걷는 인물': { en: 'Sunset beach, walking figure', ja: '夕焼けの浜辺、歩く人物', zh: '夕阳海滩，行走的人' },
  '네온 시티 드라이브': { en: 'Neon city drive', ja: 'ネオン都市ドライブ', zh: '霓虹都市驾驶' },
  '제품 광고 클로즈업': { en: 'Product ad close-up', ja: '製品広告クローズアップ', zh: '产品广告特写' },
  '숲속 아침 안개': { en: 'Misty morning forest', ja: '森の朝霧', zh: '晨雾森林' },
  '인물 시네마틱 포트레이트': { en: 'Cinematic portrait', ja: 'シネマティックポートレート', zh: '电影感人像' },
  '자동차 브랜드 필름': { en: 'Automotive brand film', ja: '自動車ブランドフィルム', zh: '汽车品牌影片' },
  '카페 브이로그': { en: 'Café vlog', ja: 'カフェVlog', zh: '咖啡馆 Vlog' },
  '우주 스페이스 씬': { en: 'Outer-space scene', ja: '宇宙シーン', zh: '外太空场景' },
  '패션 런웨이': { en: 'Fashion runway', ja: 'ファッションランウェイ', zh: '时装秀' },
  '도시 야경 타임랩스': { en: 'City night timelapse', ja: '都市夜景タイムラプス', zh: '城市夜景延时' },
  '뷰티 제품 광고': { en: 'Beauty product ad', ja: 'ビューティー製品広告', zh: '美妆产品广告' },
  '산 정상 일출': { en: 'Mountain summit sunrise', ja: '山頂の日の出', zh: '山顶日出' },
}

type Clip = {
  cap: string
  model: string
  dur: string
  ar: 'p' | 'l' | 's' // portrait 9:16, landscape 16:9, square
  grad: string
  glow: string // radial highlight position/color
  tag?: 'node' | 'control'
}

const CLIPS: Clip[] = [
  { cap: '노을 해변, 걷는 인물', model: 'Seedance 2.0', dur: '0:05', ar: 'p', grad: 'from-orange-400 via-rose-500 to-blue-800', glow: 'radial-gradient(circle at 72% 24%, rgba(255,236,180,0.9), transparent 42%)', tag: 'control' },
  { cap: '네온 시티 드라이브', model: 'Google Veo 3.1', dur: '0:08', ar: 'l', grad: 'from-indigo-600 via-fuchsia-600 to-cyan-500', glow: 'radial-gradient(circle at 30% 80%, rgba(56,189,248,0.6), transparent 45%)', tag: 'node' },
  { cap: '제품 광고 클로즈업', model: 'Runway Gen-4', dur: '0:04', ar: 's', grad: 'from-slate-700 via-zinc-600 to-amber-500', glow: 'radial-gradient(circle at 60% 30%, rgba(255,255,255,0.5), transparent 40%)' },
  { cap: '숲속 아침 안개', model: 'Luma Ray 2', dur: '0:06', ar: 'l', grad: 'from-emerald-600 via-teal-600 to-slate-800', glow: 'radial-gradient(circle at 40% 20%, rgba(190,255,210,0.55), transparent 45%)', tag: 'control' },
  { cap: '인물 시네마틱 포트레이트', model: 'Kling 2.0', dur: '0:05', ar: 'p', grad: 'from-rose-500 via-purple-600 to-slate-900', glow: 'radial-gradient(circle at 50% 30%, rgba(255,200,230,0.5), transparent 42%)' },
  { cap: '자동차 브랜드 필름', model: 'Google Veo 3.1', dur: '0:07', ar: 'l', grad: 'from-zinc-800 via-slate-700 to-red-600', glow: 'radial-gradient(circle at 70% 60%, rgba(255,120,90,0.5), transparent 45%)', tag: 'node' },
  { cap: '카페 브이로그', model: 'MiniMax Hailuo 02', dur: '0:05', ar: 'p', grad: 'from-amber-400 via-orange-500 to-rose-700', glow: 'radial-gradient(circle at 40% 25%, rgba(255,240,200,0.6), transparent 40%)' },
  { cap: '우주 스페이스 씬', model: 'Runway Aleph', dur: '0:08', ar: 'l', grad: 'from-slate-900 via-indigo-800 to-violet-700', glow: 'radial-gradient(circle at 65% 30%, rgba(160,180,255,0.55), transparent 45%)', tag: 'control' },
  { cap: '패션 런웨이', model: 'Seedance 2.0 Fast', dur: '0:04', ar: 'p', grad: 'from-pink-500 via-fuchsia-600 to-violet-700', glow: 'radial-gradient(circle at 50% 20%, rgba(255,210,240,0.5), transparent 42%)' },
  { cap: '도시 야경 타임랩스', model: 'Google Veo 3.1', dur: '0:06', ar: 'l', grad: 'from-blue-700 via-indigo-700 to-purple-800', glow: 'radial-gradient(circle at 30% 70%, rgba(120,160,255,0.55), transparent 45%)', tag: 'node' },
  { cap: '뷰티 제품 광고', model: 'Flux → Runway', dur: '0:05', ar: 'p', grad: 'from-rose-400 via-pink-500 to-purple-600', glow: 'radial-gradient(circle at 55% 28%, rgba(255,225,235,0.6), transparent 40%)', tag: 'control' },
  { cap: '산 정상 일출', model: 'Luma Ray 2', dur: '0:07', ar: 'l', grad: 'from-sky-600 via-cyan-500 to-amber-400', glow: 'radial-gradient(circle at 60% 25%, rgba(255,240,190,0.65), transparent 45%)' },
]

const ARW: Record<Clip['ar'], string> = { p: 'w-44', l: 'w-80', s: 'w-56' }

const LEGEND = ['Google Veo 3.1', 'Seedance 2.0', 'Runway Gen-4', 'Luma Ray 2', 'Kling 2.0', 'MiniMax Hailuo 02']

function ClipCard({ c, t }: { c: Clip; t: (s: string) => string }) {
  return (
    <div className={cn('group relative h-56 overflow-hidden rounded-xl border border-white/10 shadow-lg transition-transform duration-300 hover:scale-[1.03]', ARW[c.ar])}>
      <div className={cn('absolute inset-0 bg-gradient-to-br', c.grad)} />
      <div className="absolute inset-0" style={{ backgroundImage: c.glow }} />
      <div className="absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-black/70 via-black/20 to-transparent" />

      {/* 모델 배지 */}
      <span className="absolute left-2 top-2 flex items-center gap-1 rounded-md bg-black/45 px-1.5 py-0.5 text-[10px] font-bold text-white backdrop-blur-sm">
        <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" /> {c.model}
      </span>
      {/* 태그 */}
      {c.tag && (
        <span className="absolute right-2 top-2 rounded-md bg-blue-500/85 px-1.5 py-0.5 text-[9px] font-bold text-white backdrop-blur-sm">
          {c.tag === 'node' ? t('노드형') : 'ControlNet'}
        </span>
      )}
      {/* 재생 */}
      <span className="absolute left-1/2 top-1/2 grid h-11 w-11 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-white/20 backdrop-blur-sm ring-1 ring-white/40 transition-transform duration-300 group-hover:scale-110">
        <Play size={16} className="ml-0.5 text-white" fill="white" />
      </span>
      {/* 하단 캡션 */}
      <div className="absolute inset-x-0 bottom-0 flex items-end justify-between p-2.5">
        <span className="max-w-[70%] text-[11px] font-medium leading-tight text-white [text-shadow:0_1px_4px_rgba(0,0,0,0.6)]">{t(c.cap)}</span>
        <span className="rounded bg-white/20 px-1.5 py-0.5 text-[9px] font-bold text-white backdrop-blur-sm">{c.dur}</span>
      </div>
    </div>
  )
}

export function AIVideoGallery() {
  const t = useT(M)
  const row1 = CLIPS.slice(0, 6)
  const row2 = CLIPS.slice(6)
  return (
    <section className="relative overflow-hidden border-t border-white/10 py-24">
      <div className="relative mx-auto max-w-7xl px-5">
        <Reveal className="mx-auto max-w-2xl text-center">
          <SectionTag>
            <Sparkles size={13} /> {t('지금 제작되는 AI 영상')}
          </SectionTag>
          <h2 className="mt-5 text-balance text-4xl font-bold tracking-tight sm:text-5xl">
            {t('모든 최상위 모델로,')} <span className="brand-text">{t('노드형 파이프라인에서')}</span>
          </h2>
          <p className="mt-5 text-balance text-lg leading-relaxed text-[var(--text-soft)]">
            {t('프롬프트 한 줄이 레퍼런스 이미지 → ControlNet 정밀 제어 → 최상위 영상 모델을 거쳐 완성됩니다. 각 모델로 실제 생성되는 영상들입니다.')}
          </p>

          {/* 특성 태그 */}
          <div className="mt-6 flex flex-wrap items-center justify-center gap-2">
            {[
              { icon: Boxes, label: t('노드형') },
              { icon: SlidersHorizontal, label: t('ControlNet 제어') },
              { icon: Play, label: t('4K 렌더') },
            ].map((x) => {
              const Icon = x.icon
              return (
                <span key={x.label} className="inline-flex items-center gap-1.5 rounded-full border border-white/12 bg-white/[0.05] px-3 py-1.5 text-xs font-semibold text-slate-200">
                  <Icon size={13} className="text-blue-300" /> {x.label}
                </span>
              )
            })}
          </div>
        </Reveal>
      </div>

      {/* 갤러리 (2행 마퀴, 좌우 반대 방향) */}
      <Reveal delay={100} className="mt-14 space-y-4">
        <div className="marquee-mask overflow-hidden">
          <div className="marquee-track gap-4">
            {[...row1, ...row1].map((c, i) => <div key={i} className="flex-shrink-0"><ClipCard c={c} t={t} /></div>)}
          </div>
        </div>
        <div className="marquee-mask overflow-hidden">
          <div className="marquee-track marquee-rev gap-4">
            {[...row2, ...row2].map((c, i) => <div key={i} className="flex-shrink-0"><ClipCard c={c} t={t} /></div>)}
          </div>
        </div>
      </Reveal>

      {/* 작동 중인 모델 레전드 */}
      <div className="relative mx-auto mt-12 max-w-4xl px-5">
        <p className="mb-3 flex items-center justify-center gap-2 text-xs font-semibold text-[var(--text-soft)]">
          <span className="relative flex h-2 w-2">
            <span className="animate-ping-ring absolute inline-flex h-full w-full rounded-full bg-emerald-400" />
            <span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-400" />
          </span>
          {t('작동 중')}
        </p>
        <div className="flex flex-wrap justify-center gap-2">
          {LEGEND.map((m) => (
            <span key={m} className="inline-flex items-center gap-1.5 rounded-full border border-white/12 bg-white/[0.05] px-3 py-1.5 text-xs font-medium text-slate-300">
              <Check size={12} className="text-emerald-400" /> {m}
            </span>
          ))}
        </div>
      </div>
    </section>
  )
}
